### ISSUE TITLE
Traces Error

### ISSUE THREAD

**Issue by smilingbullet** [activityhistory/traces#2]
Greetings,

I'm trying to install traces and I've followed instructions mentionned on Readme.md. After compiling the project into the app, when I launch, I get a window "Traces Error" and the following message in the console:
09/11/2015 16:29:12,370 Traces[890]: Traces Error
09/11/2015 16:29:14,450 com.apple.launchd.peruser.501[152]: (org.pythonmac.unspecified.Traces.64096[890]) Exited with code: 255

Please help.
Thanks.

**Comment by acrule** [comment]
Sorry you're having trouble running Traces.

That error message is pretty cryptic. Was that the whole message?

In the meantime, you can try installing the pre-compiled app from https://github.com/activityhistory/traces/releases. Let us know if that crashes as well.

**Comment by smilingbullet** [comment]
I might be missing something but when the app crashes and I open the console, that's the only message concerning Traces that I find.

The pre-compiled app works just fine. something odd though is that the size of the pre compiled app is lower (14mo) than the local compiled one (16mo), don't know if it would help.

**Comment by aurelient** [comment]
Hi Salah, 
try launching Traces from the terminal. Move to the directory where the application is located and type Traces.app/Contents/MacOS/Traces

The error should show up in the Terminal then.

Alternatively you can open the Console application /Applications/Utilities/Console.app and look for the logs from Traces

**Comment by smilingbullet** [comment]
Hello Aurelien,

Here's the error message on the terminal:

Mac-Pro-de-Salah:MacOS Salah$ ./Traces 
Traceback (most recent call last):
  File "/Users/Salah/traces/dist/Traces.app/Contents/Resources/**boot**.py", line 54, in <module>
    _run()
  File "/Users/Salah/traces/dist/Traces.app/Contents/Resources/__boot__.py", line 49, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Users/Salah/traces/dist/Traces.app/Contents/Resources/__init__.py", line 20, in <module>
    from activity_tracker import ActivityTracker
  File "activity_tracker.pyc", line 28, in <module>
  File "sniff_cocoa.pyc", line 36, in <module>
  File "recorders/app_recorder.pyc", line 26, in <module>
ImportError: No module named accessibility
2015-11-09 18:00:27.688 Traces[416:507] Traces Error

**Comment by acrule** [comment]
Yes, it looks like we had an undocumented dependency for the accessibility python module (https://pypi.python.org/pypi/accessibility/0.4.0). This lets Traces track application events. I've updated the requirements-osx.txt file to include this. You will need to download it if you want to compile Traces locally.

The difference in size of the downloaded and locally compiled applications may have to do with the versions of python and python modules you have installed since parts of these get packaged into the app when it is compiled.

**Comment by acrule** [comment]
I think we've diagnosed the issue as an undocumented dependency and taken care of the issue.
